language: node_js

node_js:
   - node

before_script:
   - npm install -g --silent firebase-tools
   - npm install -g --silent @angular/cli

script:
   - ng build --prod

after_success:
  - test $TRAVIS_BRANCH = "main" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    recipients:
      - leonidas.ollima@gmail.com
    on_failure: always
    on_success: never
